version: 1.0.{build} 
image: Visual Studio 2017

pull_requests:  
  do_not_increment_build_number: true
branches:  
  only:
  - master
build_script: 
  - cmd: build.bat canary
test: off
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
artifacts:  
- path: .\build\output\_packages\*.nupkg
  name: NuGet
nuget:
  disable_publish_on_pr: true
  account_feed: true
  project_feed: true
