name: Build and publish snapshot packages
on:
  push:
    paths-ignore:
      - 'README.md'
      - '.editorconfig'
    branches:
      - "*"
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: |
        git fetch --prune --unshallow --tags
        echo exit code $?
        git tag --list
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.100'
  
    - run: dotnet nuget add source --username Bit-Quill --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Bit-Quill/index.json"  
      name: Add GitHub NuGet Repository as a Package Source
    - run: ./build.sh build -s true
      name: Build

    - run: ./build.sh generatepackages -s true
      name: Generate local nuget packages

    - uses: actions/upload-artifact@v2
      with:
        name: nuget-packages
        path: build/output/*

    - run: ./build.sh validatepackages -s true
      name: "validate *.npkg files that were created"

    - name: publish canary packages github package repository
      #if: github.event_name == 'push' && startswith(github.ref, 'refs/heads')
      shell: bash
      run:  |
         dotnet nuget push 'build/output/*Xunit*.nupkg' -s github -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate --no-symbols true